version: '3'
 
services:
    db:
        build:
           context: .
        # restart: always
        image: postgres:latest          
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: password
            POSTGRES_DB: stock_db
            POSTGRES_PORT_5432_TCP_PORT: 5432
        ports:
            #- "5432:5432"
            - "15432:5432"            
        volumes:
            - ./stock_db:/stock_db
            - db-data:/var/lib/postgresql/data
volumes:
    db-data: